from ai_equity_research_copilot_backend.financial_tables import financial_table_facts


def test_vertical_segment_table_keeps_period_scale_and_source_context():
    text = """SEGMENT RESULTS OF OPERATIONS
(In millions, except percentages)
2031
2030
Percentage
Change
Enterprise Services
Revenue
$ 124,810
$ 105,120
19%
Operating income
$ 14,121
$ 12,140
16%
Consumer Devices
Revenue
$ 36,123
$ 31,912
13%
"""
    facts = financial_table_facts(text)
    assert len(facts) == 3
    first = facts[0]
    assert first.label == "Enterprise Services: Revenue"
    assert text[slice(*first.row_span)] == "Revenue\n$ 124,810\n$ 105,120\n19%"
    assert "2031\n2030\nPercentage\nChange" in first.source_excerpt
    assert "(In millions, except percentages)" in first.source_excerpt
    assert text[slice(*first.context_span)] == "Enterprise Services"
    assert facts[-1].label == "Consumer Devices: Revenue"


def test_interleaved_change_columns_do_not_shift_year_values():
    text = """The following table shows regional sales (dollars in millions):
2032 Change 2031 Change 2030
North $ 42,353 7 % $ 39,580 3 % $ 38,120
South 24,377 (4) % 25,912 (8) % 28,159
"""
    facts = financial_table_facts(text)
    assert len(facts) == 2
    assert text[slice(*facts[0].header_span)] == "The following table shows regional sales (dollars in millions):\n2032 Change 2031 Change 2030"
    assert "North $ 42,353 7 % $ 39,580 3 % $ 38,120" in facts[0].source_excerpt
    assert "South 24,377 (4) % 25,912 (8) % 28,159" in facts[1].source_excerpt


def test_full_dates_accounting_negatives_and_exact_precision():
    text = """STATEMENTS OF CASH FLOWS
(In millions)
Years ended
September 29,
2031 September 30,
2030
Operating activities:
Cash generated by operating activities 123,456 112,345
Purchases of property and equipment ( 12,710.5 ) ( 11,020 )
"""
    facts = financial_table_facts(text)
    assert len(facts) == 2
    assert "September 29,\n2031 September 30,\n2030" in facts[0].source_excerpt
    assert "(In millions)" in facts[1].source_excerpt
    assert text[slice(*facts[1].row_span)] == "Purchases of property and equipment ( 12,710.5 ) ( 11,020 )"
    assert "-12.7105" not in facts[1].source_excerpt


def test_footnotes_wrapped_ratios_are_not_inferred_percent_or_scaled():
    text = """(in millions, except per share and ratios)
1Q31 4Q30 3Q30
Selected ratios and metrics
Common equity Tier 1 capital ratio (c)(d)
14.2 (f)
14.8 15.1
Return on assets 1.4 % 1.3 % 1.2 %
"""
    facts = financial_table_facts(text)
    assert len(facts) == 2
    assert facts[0].label.endswith("Common equity Tier 1 capital ratio")
    assert "14.2 (f)\n14.8 15.1" in facts[0].source_excerpt
    assert "%" not in facts[0].source_excerpt
    assert "Return on assets 1.4 % 1.3 % 1.2 %" in facts[1].source_excerpt


def test_per_share_counts_and_dashes_do_not_become_millions_or_zero():
    text = """(In millions, except per share and employee data)
2031 2030
Earnings per share
Basic $ 4.13 $ 3.20
Employees 2500 2400
Cash flows 1,001 —
"""
    facts = financial_table_facts(text)
    assert len(facts) == 3
    assert "Earnings per share\n...\nBasic $ 4.13 $ 3.20" in facts[0].source_excerpt
    assert facts[1].label == "Employees" and "Employees 2500 2400" in facts[1].source_excerpt
    assert facts[2].label == "Cash flows" and facts[2].source_excerpt.endswith("Cash flows 1,001 —")
    assert "Earnings per share" not in facts[1].source_excerpt


def test_ambiguous_headers_unlabelled_and_wrong_width_rows_are_rejected():
    assert not financial_table_facts("2031 Acquisitions 2030\nRevenue 500 200 300")
    assert not financial_table_facts("(In millions)\nRevenue 500 300")
    assert not financial_table_facts("2031 2030\n500 300")
    assert not financial_table_facts("2031 2030\nRevenue 500 300 100")
    assert not financial_table_facts("Revenue was 500 in 2031 and 300 in 2030.")


def test_prose_ends_table_instead_of_leaking_units_to_later_numbers():
    text = "2031 2030\nRevenue 500 300\nRevenue increased because demand grew.\nOther metric 20 10"
    assert len(financial_table_facts(text)) == 1


def test_explicit_share_unit_exception_is_respected():
    text = "(In millions, except number of shares, which are reflected in thousands)\n2031 2030\nCommon shares outstanding 2500 2400\nTotal assets 42000 38000"
    facts = financial_table_facts(text)
    assert len(facts) == 2
    assert "except number of shares, which are reflected in thousands" in facts[0].source_excerpt
    assert facts[0].source_excerpt.endswith("Common shares outstanding 2500 2400")
    assert facts[1].source_excerpt.endswith("Total assets 42000 38000")


def test_duplicate_years_without_duration_groups_are_rejected():
    text = "(In millions)\nThree Months Ended Six Months Ended\n2031 2030 2031 2030\nRevenue 100 90 210 190"
    assert not financial_table_facts(text)


def test_percentage_exception_does_not_scale_an_unmarked_margin():
    text = "(In millions, except percentages)\n2031 2030\nGross margin 54.1 53.2"
    assert not financial_table_facts(text)


def test_new_percentage_subsection_does_not_inherit_money_units():
    text = "(In millions)\n2031 2030\nRevenue 1000 900\n(Percent)\nGross margin 54.1 53.2"
    facts = financial_table_facts(text)
    assert len(facts) == 1 and facts[0].label == "Revenue"
    assert "Gross margin" not in facts[0].source_excerpt


def test_headcount_employee_exception_is_not_scaled():
    text = "(In millions, except employees)\n2031 2030\nHeadcount 1500 1400"
    row, = financial_table_facts(text)
    assert row.source_excerpt.endswith("Headcount 1500 1400")
    assert "except employees" in row.source_excerpt


def test_standalone_currency_cells_retain_the_correct_row_label():
    text = "(In millions)\n2031\n2030\nEnterprise Services\nRevenue\n$\n124,810\n$\n105,120"
    facts = financial_table_facts(text)
    assert len(facts) == 1
    assert facts[0].label == "Enterprise Services: Revenue"
    assert facts[0].source_excerpt.endswith("Revenue\n$\n124,810\n$\n105,120")


def test_explicit_change_cell_and_caption_currency_are_preserved():
    text = "The following table shows regional sales (dollars in millions):\n2031 2030 Change\nNorth 1000 800 25%"
    facts = financial_table_facts(text)
    assert len(facts) == 1
    assert "(dollars in millions)" in facts[0].source_excerpt
    assert "2031 2030 Change" in facts[0].source_excerpt
    assert facts[0].source_excerpt.endswith("North 1000 800 25%")


def test_visually_reordered_change_header_uses_explicit_percent_cell():
    text = "(In millions, except percentages)\nThree Months Ended\nSeptember 30,\nPercentage\nChange\n2031\n2030\nRevenue\n$\n1000\n$\n800\n25%"
    facts = financial_table_facts(text)
    assert len(facts) == 1
    assert "September 30,\nPercentage\nChange\n2031\n2030" in facts[0].source_excerpt
    assert facts[0].source_excerpt.endswith("Revenue\n$\n1000\n$\n800\n25%")


def test_reordered_change_header_without_explicit_percent_is_ambiguous():
    assert not financial_table_facts("Change 2031 2030\nRevenue 1000 800 25")


def test_explicit_capital_approach_groups_preserve_dates_and_percent_cells():
    text = """Standardized Advanced
(in millions, except ratios) March 31, 2031
December 31, 2030
Capital ratio requirements (a)
March 31, 2031
December 31, 2030
Capital ratio requirements (a)
Risk-based capital metrics:
CET1 capital 290000 280000 290000 280000
CET1 capital ratio 14.2 % 14.5 % 11.4 % 14.0 % 14.1 % 11.4 %
Tier 1 capital ratio 15.3 15.4 13.0 15.2 15.3 13.0
"""
    facts = financial_table_facts(text)
    assert len(facts) == 2  # Incomplete amount row is still rejected.
    assert "Standardized Advanced" in facts[0].source_excerpt
    assert facts[0].source_excerpt.count("March 31, 2031") == 2
    assert facts[0].source_excerpt.count("December 31, 2030") == 2
    assert facts[0].source_excerpt.count("Capital ratio requirements (a)") == 2
    assert facts[0].source_excerpt.endswith("CET1 capital ratio 14.2 % 14.5 % 11.4 % 14.0 % 14.1 % 11.4 %")
    assert facts[1].source_excerpt.endswith("Tier 1 capital ratio 15.3 15.4 13.0 15.2 15.3 13.0")
    assert "%" not in facts[1].source_excerpt


def test_grouped_header_without_matching_period_blocks_is_rejected():
    text = "Standardized Advanced\n2031 2030 2031 2029\nCET1 capital ratio 14.2% 14.5% 14.0% 14.1%"
    assert not financial_table_facts(text)


def test_requirement_column_without_group_is_not_assigned_a_date():
    text = "(in millions, except ratios)\nMarch 31, 2031\nDecember 31, 2030\nCapital ratio requirements (a)\nLeverage ratio 6.6 % 6.9 % 4.0 %"
    facts = financial_table_facts(text)
    assert len(facts) == 1
    assert "Capital ratio requirements (a)" in facts[0].source_excerpt
    assert facts[0].source_excerpt.endswith("Leverage ratio 6.6 % 6.9 % 4.0 %")


def test_per_common_share_amounts_are_not_scaled_by_the_money_caption():
    text = "(In millions, except per share amounts)\n2031 2030\nCash dividends declared per common share\n$ 3.12\n$ 2.90"
    facts = financial_table_facts(text)
    assert len(facts) == 1
    assert "except per share amounts" in facts[0].source_excerpt
    assert facts[0].source_excerpt.endswith("Cash dividends declared per common share\n$ 3.12\n$ 2.90")


def test_explicit_percentage_section_overrides_money_caption():
    text = "(In millions, except ratios)\n2031 2030\nPercentage of portfolio based on carrying value\nNo score available 0.2 0.3"
    facts = financial_table_facts(text)
    assert len(facts) == 1
    assert "Percentage of portfolio based on carrying value\n...\nNo score available 0.2 0.3" in facts[0].source_excerpt
    wrapped = "(In millions, except ratios)\n2031 2030\npercentage of total net\nrevenue\n25 26"
    row, = financial_table_facts(wrapped)
    assert "percentage of total net\n...\nrevenue\n25 26" in row.source_excerpt


def test_numeric_allowance_annotation_is_not_misidentified_as_data_cells():
    text = "(In millions)\n2031 2030\nCurrent assets:\nAccounts receivable, net of allowance for doubtful accounts of $ 600 and $ 800\n52,000\n49,000"
    facts = financial_table_facts(text)
    assert len(facts) == 1
    assert "$ 600 and $ 800" in facts[0].label
    assert facts[0].source_excerpt.endswith("Accounts receivable, net of allowance for doubtful accounts of $ 600 and $ 800\n52,000\n49,000")


def test_first_row_currency_can_be_inherited_with_an_exact_source_basis():
    text = "(In millions)\n2031 2030\nOpening cash $ 1000 $ 900\nOperating cash 1200 1100"
    facts = financial_table_facts(text)
    assert len(facts) == 2
    assert "Opening cash $ 1000 $ 900" in facts[1].source_excerpt
    assert facts[1].source_excerpt.endswith("Operating cash 1200 1100")
    assert facts[1].label == "Operating cash"  # Currency basis is not a relevance label.


def test_currency_inheritance_rejects_conflicts_and_nonmoney_exceptions():
    text = "(In millions, except per share and employee data)\n2031 2030\nOpening cash $ 1000 $ 900\nEmployees 1000 900\nBasic earnings per share 2.1 1.9\nOperating cash 1200 1100\nEuro reserves € 600 € 500"
    facts = financial_table_facts(text)
    assert len(facts) == 5
    assert all("Opening cash" not in fact.source_excerpt for fact in facts if fact.label != "Opening cash")


def test_currency_inheritance_keeps_change_columns_as_percentages():
    text = "(In millions, except percentages)\nPercentage Change\n2031 2030\nRevenue $ 1000 $ 800 25%\nOperating income 200 100 100%"
    facts = financial_table_facts(text)
    assert len(facts) == 2
    assert "Revenue $ 1000 $ 800 25%" in facts[1].source_excerpt
    assert facts[1].source_excerpt.endswith("Operating income 200 100 100%")


def test_unparsed_mixed_currency_row_also_prevents_inheritance():
    text = "(In millions)\n2031 2030\nOpening cash $ 1000 $ 900\nOperating cash 1200 1100\nEuro reserves € 600 € 500 € 400"
    facts = financial_table_facts(text)
    assert len(facts) == 2
    assert "Opening cash" not in facts[1].source_excerpt


def test_explicit_usd_millions_caption_keeps_scale_and_original_accounting_notation():
    text = "Results (USD millions)\n2034 2033\nOperating income (17) 28\nNet income (23) 21"
    facts = financial_table_facts(text)
    assert len(facts) == 2
    assert "USD millions" in facts[0].source_excerpt
    assert facts[0].source_excerpt.endswith("Operating income (17) 28")
    assert facts[1].source_excerpt.endswith("Net income (23) 21")


def test_row_contract_contains_only_source_structure_and_exact_excerpts():
    from dataclasses import asdict

    text = "(In millions)\n2031 2030\nCash (100) 90\nUnknown — –"
    rows = financial_table_facts(text)
    assert len(rows) == 1  # An entirely missing row is not invented as zero.
    assert set(asdict(rows[0])) == {"label", "source_excerpt", "header_span", "row_span", "context_span"}
    assert rows[0].source_excerpt.endswith("Cash (100) 90")
    assert text[slice(*rows[0].header_span)] in rows[0].source_excerpt
    assert text[slice(*rows[0].row_span)] in rows[0].source_excerpt
